name: Update README with today's date
run-name: Updating README with today's date

on: [push]
  # schedule:
    # - cron: '0 0 * * *' # Runs everyday at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write today's date into README
        run: echo $(date +%Y-%m-%d) > README.md
      - name: stage changed files
        run: git add README.md
      - name: commit changed files
        run: git commit -m "Update README with today's date"
      - name: push changed README
        run: git push origin main
